apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: thwqra08n-java-springboot 
  janus-idp.io/tekton: thwqra08n-java-springboot
  backstage.io/kubernetes-id: thwqra08n-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: thwqra08n-java-springboot
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  